### ISSUE TITLE
Add new attribute to a data structure

### ISSUE THREAD

**Issue by darkaeon10** [apiaryio/api-blueprint#253] opened 2015-08-13 02:40 UTC
Hi, in my JSON response, I have an array, in which there are objects which I represent through a data structure.  However, I want to add a new attribute to the data structure for this specific response. For example:

![apiary screenshot](https://cloud.githubusercontent.com/assets/1049495/9241602/2eb58c14-41a8-11e5-83e0-4b6deb1858f6.png)

However, the new attribute shows up on Apiary.io as *"undefined": null*. Am I doing something wrong?

**Comment by zdne** [comment] 2015-08-13 07:34
@darkaeon10 the MSON syntax looks good. I bet this is caused by Apiary not fully supporting MSON rendering – see #191

**Comment by kylef** [comment] 2015-08-13 12:37
Hi @darkaeon10, I'm having a bit of trouble trying to reproduce this one. Would you be able to share with us an example blueprint that produces this problem. I've built the following which looks identical (except the parameter names):

```apib
## Users [/user]
### Retrieve a user [GET]
+ Response 200 (application/json)
    + Attributes (User)
        + friends (array, required)
            + (User)
                + relation: family (required)
            + (User)
                + relation: friend (required)

## Data Structures
### User
+ username: kyle
```

Which get's rendered as expected in Apiary:

![screen shot 2015-08-13 at 13 35 58](https://cloud.githubusercontent.com/assets/44164/9249825/432c5886-41c0-11e5-9d1a-b29c916a73c4.png)

The JSON representation:

```json
{
  "friends": [
    {
      "relation": "family",
      "username": "kyle"
    },
    {
      "relation": "friend",
      "username": "kyle"
    }
  ],
  "username": "kyle"
}
```

Thanks!

**Comment by darkaeon10** [comment] 2015-08-14 10:54
@zdne Ah yes, I am aware of #191 and I'm looking forward to the future release resolving that issue. However, sorry if I wasn't being clear, but I was referring to the attribute appearing as *"undefined": null* in the JSON representation (see picture below).

![json](https://cloud.githubusercontent.com/assets/1049495/9272460/395fa2ea-42b5-11e5-93fd-6a258bcadf02.png)


@kylef  Hi, below is the blueprint that produces the said JSON representation (shown in the picture above). 
![blueprint](https://cloud.githubusercontent.com/assets/1049495/9272478/6999e542-42b5-11e5-9211-c552b9446486.png)

I've played around with it a bit, and noticed that the bug occurs when I wrap the users array within a data object. That is, the JSON looks alright if I remove the *data* object and place the *users* array directly under *Attributes*.

P.S. How do you type in API blueprints here on Github? I've tried directly copy-pasting the blueprint here and it looks weird because it follows Github's Markdown syntax. Hence, the screenshots instead of text, and consequently disallowing you guys from copy-pasting my sample blueprint. Sorry about that.

**Comment by kylef** [comment] 2015-08-14 11:04
@darkaeon10 You can use a code-block with back ticks as follows:

    ```apib
    ## My Awesome Blueprint
    ```

**Comment by pksunkara** [comment] 2015-08-14 11:05
@darkaeon10 This might be an issue of rendering deeply nested member types which has been already fixed in development branch of drafter but I verify it once and get back to you.

**Comment by darkaeon10** [comment] 2015-08-17 01:47
@kylef Thanks! 

@pksunkara  Alright, thank you!

**Comment by zdne** [comment] 2015-12-01 08:11
@pksunkara what is status of this?

**Comment by pksunkara** [comment] 2015-12-09 10:54
This is working now and is released on drafter and protagonist.

**Closed** 2015-12-09 10:55 UTC
