### ISSUE TITLE
Rendered schema for arrays in Data Structures is incorrect

### ISSUE THREAD

**Issue by winniehell** [apiaryio/api-blueprint#254] opened 2015-08-14 12:38 UTC
For me

```markdown
## MyObject [/objects]

+ Attributes (object)

### List objects [GET]

+ Response 200 (application/json)
    + Attributes (object)
        + many (array[MyObject])
        + one (MyObject)
````

leads to the following schema:

```json
{
  "type": "object",
  "properties": {
    "many": {
      "type": "array"
    },
    "one": {
      "type": "object"
    }
  },
  "$schema": "http://json-schema.org/draft-04/schema#"
}
```

Shouldn't the schema be:

```json
{
  "type": "object",
  "properties": {
    "many": {
      "type": "array",
      "items": {
        "type": "object"
      }
    },
    "one": {
      "type": "object"
    }
  },
  "$schema": "http://json-schema.org/draft-04/schema#"
}
```

The generated body is correct:

```json
{
  "many": [
    {}
  ],
  "one": {}
}
```

**Comment by pksunkara** [comment] 2015-08-14 12:45
@winniehell It is a known bug in our schema generation of a data structure and we have it on our radar. Thanks :)

**Comment by pksunkara** [comment] 2015-08-14 12:47
Duplicate of apiaryio/mson#31

**Closed** 2015-08-14 12:47 UTC
Labels: duplicate

**Comment by winniehell** [comment] 2015-08-14 12:53
Thank you for the reply and sorry for reporting at the wrong place!

**Comment by neerajjain92** [comment] 2021-01-12 18:07
@pksunkara When are you planning to fix this?

**Comment by pksunkara** [comment] 2021-01-12 19:38
Never. You will have to ask someone from Apiary. I don't have any interest in forking API Blueprint or MSON.
