### ISSUE TITLE
Reuse headers and attributes?

### ISSUE THREAD

**Issue by winniehell** [apiaryio/api-blueprint#259] opened 2015-08-27 13:38 UTC
I have a model which defines headers and a model which defines attributes:

```markdown
## Fast [/fast]

+ Model
    + Headers

            X-Fast-Processing: true

## Things [/things]

+ Attributes (object)
    + name (string)
```

Now I want to use the headers in GET- and PUT-request and the attributes in GET-response and PUT-request. The following does not work:

```markdown
### Get Things [GET]

+ Request
    [Fast ][]

+ Response 200 (application/json)
    + Attributes (Things)

### Put Things [PUT]

+ Request (application/json)
    [Fast ][]
    + Attributes (Things)

+ Response 200

            Everything fine.
```

Is there any way to achieve this?

**Comment by winniehell** [comment] 2015-08-27 13:40
Putting the heads from `Fast` into the `Things` model does not work because I need to reuse the `Fast`-headers in other resources, too.

**Comment by pksunkara** [comment] 2015-08-27 22:33
@winniehell The `Model` you are defining is a payload. `Request` and `Response` are payloads too. So, you can use the following the syntax to reference the payload

```
+ Request
    [Fast][]
```

But you can not combine it with other parts in a payload.

PS: Currently, you cannot reuse headers.

**Comment by pksunkara** [comment] 2015-08-27 22:34
This might be a duplicate of #17 but I will leave it to @zdne.

**Comment by winniehell** [comment] 2015-08-27 22:52
@pksunkara: yep, looks duplicate to me - I don't know why I didn't find that issue. Thank you for the hint! :+1:

**Comment by pksunkara** [comment] 2015-08-27 22:52
I would like to keep this issue open and let @zdne decide since #17 is linked to Traits.

**Comment by winniehell** [comment] 2015-08-27 23:07
Sure, I don't mind. :tropical_fish: 

My primary intention was to find out how to reuse headers and attributes. That problem seems so be solved by Traits as far as I understand it:

```markdown
## Fast [/fast]

+ Trait Fast
    + Request Headers

            X-Fast-Processing: true

## Things [/things]

+ Trait Thing
    + Properties
        + name (string)

### Get Things [GET]

+ Request
    + Traits
        + [Fast][]

+ Response 200 (application/json)
    + Traits
        + [Things][]

### Put Things [PUT]

+ Request (application/json)
    + Traits
        + [Fast][]
        + [Things][]

+ Response 200

            Everything fine.
```

Or do I get something wrong?

**Comment by pksunkara** [comment] 2015-08-27 23:10
@winniehell Well, the traits was still in proposal stage and is currently in an uncertain state since we now have MSON. So, please keep a look out on further updates.

**Comment by zdne** [comment] 2015-08-28 07:11
@winniehell @pksunkara I plan to update and close the traits issue during the course of the next wee. To  the original question, reusable headers using MSON syntax are definitely planned.

**Comment by zdne** [comment] 2015-09-28 16:15
RFC proposal of syntax addressing this issue: https://github.com/apiaryio/api-blueprint-rfcs/pull/3. 

Please track and comment on the RFC.

Thank you!

**Closed by zdne** 2015-09-28 16:15 UTC
Labels: question
